
libdir = /home/local/ZOHOCORP/muguntha-pt5620/Desktop/pg11/lib
MODULES = bw_sm bw_topper
EXTENSION = bwstudentsmarkstoppers
DATA = bwstudentsmarkstoppers--0.0.1.sql
PG_CONFIG = /home/local/ZOHOCORP/muguntha-pt5620/Desktop/pg11/bin/pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
PG_CPPFLAGS = -g
include $(PGXS)