libdir = /home/local/ZOHOCORP/muguntha-pt5620/Desktop/postgresql-11.4/src/include
# $(info $$libdir is [${libdir}])

MODULES = bw_sm
EXTENSION = bw_sm
DATA = bw_sm--0.0.1.sql
PG_CONFIG = /home/local/ZOHOCORP/muguntha-pt5620/Desktop/pg11/bin/pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
PG_CPPFLAGS = -g
include $(PGXS)